steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-east1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/revrecover-frontend', '--build-arg', 'VITE_API_URL=$_BACKEND_URL', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-east1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/revrecover-frontend']
images:
  - 'us-east1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/revrecover-frontend'
